import ImageInput from "@components/imageInput";
import axios from "axios";
import { useFormik } from "formik";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { setFieldValue, values } = useFormik({
    initialValues: {
      image: null,
      art: null,
    },
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    if (values.art && values.image) {
      fetch("https://9nzxtf.deta.dev/", {
        body: {
          image: "s",
          art: "k",
        },
        method: "POST",
        headers: {
          "X-API-Key": process.env.deta_key,
          "Content-Type": "application/json",
        },
      })
        .then((res) => res.json())
        .then((res) => console.log(res))
        .catch((err) => {
          console.log(err);
        });
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-[30px] space-y-[30px]">
        <h3 className="text-purple">Sanatsal Resim</h3>
        <form className="space-y-[30px]" onSubmit={handleSubmit}>
          <ImageInput
            onSelect={(image) => {
              setFieldValue("image", image);
            }}
            alt="baz resim"
            title={"Resim"}
          />
          <ImageInput
            onSelect={(image) => {
              setFieldValue("art", image);
            }}
            alt="sanatsal resim"
            variant={"filled"}
            title={"Sanatsal Resim"}
          />
          <button
            type="submit"
            className="bg-green w-full py-[12px] text-white rounded-[4px] hover"
          >
            İşle
          </button>
        </form>
      </main>
    </div>
  );
}
